Pass template context as dict instead of as Context
Zbooni/django-mailviews pull request #1
Opened 2018-01-19 13:13 UTC by arnoldchoa91

https://docs.djangoproject.com/en/1.11/releases/1.11/#django-template-backends-django-template-render-prohibits-non-dict-context

2018-01-21 07:44 UTC, lemuelf requested changes

2018-01-21 07:44 UTC, lemuelf commented on mailviews/messages.py
>          :rtype: :class:`django.template.Context`
Please update this docstring line.

2018-01-22 08:19 UTC, arnoldchoa91 commented
@lemuelf Updated the docstrings and removed unused imports. Please review.

2018-01-23 08:36 UTC, lemuelf commented
Please create a branch for Django 1.11 fixes and set that as this pull requests base.  We'd rather keep master in-synch with the upstream repository and keep our own fixes in another branch.

2018-01-23 08:57 UTC, arnoldchoa91 commented
@lemuelf Ok, I've created the `django-1.11-migration` branch and set it as this PR's base branch.

2018-01-23 09:01 UTC, lemuelf approved these changes

2018-01-23 09:37 UTC, merged